declare module 'slash2';
declare module 'antd-theme-webpack-plugin';
declare module '*.css';
declare module '*.less';
declare module '*.scss';
declare module '*.sass';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
declare module 'omit.js';
declare module 'react-copy-to-clipboard';
declare module 'react-fittext';
declare module 'jsencrypt';
declare module '@antv/data-set';
declare module 'insert-css';
declare module 'dagre';
declare module 'js-base64';
declare module 'rehype-highlight';
declare module 'react-codemirror2';
declare module 'jsonlint-mod';
declare module 'braft-utils';
declare module 'braft-editor';

declare const REACT_APP_ENV: 'test' | 'dev' | 'pre' | false;
